# docker-compose build
# docker-compose up

version: '3.9'

services:
  blockchain:
    image: blockchain
    build:
      context: ./
      args:
        NAME_PROJECT: blockchain
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on: 
      - opencloser
  opencloser:
    image: opencloser
    build:
      context: ./
      args:
        NAME_PROJECT: opencloser
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    depends_on: 
      - register
  register:
    image: register
    build:
      context: ./
      args:
        NAME_PROJECT: register
      dockerfile: Dockerfile
    ports:
      - "5003:80"
    depends_on: 
      - wallet
  wallet:
    image: wallet
    build:
      context: ./
      args:
        NAME_PROJECT: wallet
      dockerfile: Dockerfile
    ports:
      - "5004:80"